/**
   @mainpage Crossing Minimization

Programs generated by 'make -f makefile-instance-generation':

     - random_geometric_tree: creates a minimum spanning tree of randomly
     chosen points in a rectangle; the tree is layered by choosing a root and
     extending each root-leaf path from layer 1 to layer ell and back again
     as many times as needed
     - randomize_ord: takes an ord file and randomly permutes the nodes on
     each layer
     - randomize_dot: randomly permutes the edges of a dot file 


    Copyright (C) 2009 Matthias Stallmann, Saurabh Gupta.
    Contact: matt_stallmann AT ncsu DOT edu

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License (gnu-public-license.txt) along with this program.

    If not, write to the
     Free Software Foundation, Inc.,
     51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.

@todo There is some functional duplication among the code in this directory
 and the code in java-utilities and in ../src. Eventually the code here should
 be merged with that in src and use a common internal dag
 representation. Ditto the LayerAssignment program in ../java-utilities. The
 only special case is ../java-utilities/DagDisplay.java. 

**/

/* Latest version $Id: 0-instance-generation-mainpage.h 34 2012-01-06 18:33:05Z mfms $ */

/*  [Last modified: 2012 01 06 at 18:31:44 GMT] */
