#! /bin/bash

## createConnectedDagClass - a script for creating a class of random dags
# based on a profile that specifies the number of nodes, edges, and layers,
# as well as a skew factor that determines both the maximum degree and the
# variance in number of nodes per layer.
# Note: leaves a file called stats.out in the class directory
#
# IMPORTS:
#   - create_random_dag from ../src
#
# @author Matt Stallmann
# @date 2011/06/05
# $Id: createConnectedDagClass 107 2015-04-20 19:00:18Z mfms $

size=32

if [ $# != 6 ]; then
    echo "Usage: createConnectedDagClass"\
          "TARGET_ROOT_DIRECTORY BASE_NAME NODES EDGES LAYERS SKEW"
    echo " TARGET_ROOT_DIRECTORY is the parent directory for"\
          " the random class directory"
    echo "BASE_NAME is used to name the directory and the files within it"
    echo "The directory is called BASE_NAME-rnd"
    echo " and each new .dot/.ord pair has prefix BASE_NAME-rnd-xxx,"
    echo " where xxx is a three-digit sequence number (the seed)."
    echo "NODES, EDGES and LAYERS self-explanatory"
    echo "SKEW determines max degree and variance in nodes per layer"
    exit 1
fi

script_directory=${0%/*}
bin_directory=$script_directory/../src
current_directory=$PWD

target_root_directory=$1
shift
base_name=$1
shift
nodes=$1
shift
edges=$1
shift
layers=$1
shift
skew=$1

tag=rnd

if [ ! -d $target_root_directory ]; then
    if [ ! -f $target_root_directory ]; then
        mkdir $target_root_directory
    else
        echo "Output directory $target_root_directory exists as a file."
        echo "Cannot proceed with script $0"
        exit 1
    fi
fi
class_dir=$target_root_directory/$base_name-$tag
if [ -d $class_dir ]; then
    echo "$class_dir already exists."
    echo -n "Replace it (y/n) [n]? "
    read answer
    if [ $answer != "y" ]; then
        echo "Not replacing directory;"
        echo "script $0 is terminating."
        exit 1
    else
        rm -rf $class_dir
    fi
elif [ -f $class_dir ]; then
    echo "$class_dir is a regular file;"
    echo "will not replace it with a directory."
    exit 1
fi

creation_program=$bin_directory/create_random_dag

# get here only if $target_root_directory exists and $class_dir doesn't.
mkdir $class_dir
echo "Creating a class in directory $class_dir"
pushd $class_dir &> /dev/null
stat_file=stats.out
index=1
while [[ $index -le $size ]]; do
    instance_base=$base_name-$tag-`echo $index | awk '{printf "%03d",$1;}'`
    seed=$index
    echo "----------------- $instance_base ----------------" >> $stat_file
    echo -n "instance=$instance_base nodes=$nodes edges=$edges layers=$layers"
    echo " skew=$skew seed=$seed"
    $creation_program $instance_base $nodes $edges $layers $skew $seed >> $stat_file
    echo "_________________________________________________" >> $stat_file
    echo "" >> $stat_file
    index=$(( $index + 1 ))
done
popd &> /dev/null

#  [Last modified: 2014 03 31 at 18:44:39 GMT]
