#!/bin/bash
# dot+ord2sgf - creates an sgf file from a dot and an ord file
# Uses dot_and_ord_to_sgf in ../src
#
# $Id: dot+ord2sgf 66 2014-03-29 16:58:11Z mfms $

if [ $# != 2 ]; then
    echo "Usage $0 DOT_FILE_NAME ORD_FILE_NAME"
    echo "  converts the dot and ord file to an sgf file;"
    echo "  the sgf file has a basename based on the ord file"
    echo "  and will be in the current directory"
fi

dot_file_name=$1
ord_file_name=$2
script_directory=${0%/*}
basename=`basename $ord_file_name .ord`
executable=$script_directory/../src/dot_and_ord_to_sgf
echo "c created by dot+ord2sgf, date/time = `date -u`" > $basename.sgf
echo 'c $Id: dot+ord2sgf 66 2014-03-29 16:58:11Z mfms $' >> $basename.sgf
$executable $dot_file_name $ord_file_name >> $basename.sgf

#  [Last modified: 2014 03 29 at 16:41:36 GMT]
