#! /bin/bash
# twoRandomEdgeHeuristics - a specialized script for the 2016 ALENEX paper.

# Runs one heuristic after another on a class in four combinations:
# deterministic/deterministic, deterministic/random, random/deterministic,
# and random/random; arguments to min_crossings are hard-wired for specific
# experiments.

# The script is specialized for bottleneck crossings

DEFAULT_ITERATIONS=40000
PREPROCESSOR=dfs

if [ $# -ne 4 ]; then
    echo "Usage: twoRandomEdgeHeuristics class result_dir heuristic_1 heuristic_2"
    echo " runs heuristic_1 followed by heuristic_2 on the given class"
    echo "  deterministic/deterministic, deterministic/random, random/deterministic, and random/random"
    echo " results will be in result_dir with files named:"
    echo "  $PREPROCESSOR+heuristic_1-x"
    echo "  $PREPROCESSOR+heuristic_1+heuristic_2-xy"
    echo "  where x and y can be D or R for deterministic or random, respectively"
    exit 1
fi

# The runHeuristic script is in this directory, but this path needs to be
# absolute to ensure portability of the script (can be run from anywhere)
script_directory=${0%/*}
pushd $script_directory
script_directory=$PWD
popd

class=$1
result_dir=$2
heuristic_1=$3
heuristic_2=$4
iterations=$DEFAULT_ITERATIONS

# need absolute paths
result_dir=$PWD/$result_dir
class=$PWD/$class

echo $class

if [ -n $PREPROCESSOR ]; then
    prefix=$PREPROCESSOR+
fi

# run random variations first

# directory where the runs are done; outputs (.ord files) of the runs of
# heuristic_1 are named basename-R-heuristic_1.ord
working_directory=$class-R
mkdir $working_directory

# clean up any junk from previous runs
rm -f $working_directory/*.dot $working_directory/*.ord

cp $class/*.dot $class/*.ord $working_directory
pushd $working_directory

$script_directory/runHeuristicR $working_directory $result_dir R -h $heuristic_1 -p $PREPROCESSOR -i $iterations

mvsed -s "s/\.dot/-R-$prefix${heuristic_1}_edge\.dot/" *.dot

$script_directory/runHeuristic $working_directory $result_dir RD -h $heuristic_2 -i $iterations
$script_directory/runHeuristicR $working_directory $result_dir RR -h $heuristic_2 -i $iterations

popd

# now run two variations that start deterministically

# directory where the runs are done; outputs (.ord files) of the runs of
# heuristic_1 are named basename-R-heuristic_1.ord
working_directory=$class-D
mkdir $working_directory

# clean up any junk from previous runs
rm -f $working_directory/*.dot $working_directory/*.ord

cp $class/*.dot $class/*.ord $working_directory
pushd $working_directory

$script_directory/runHeuristic $working_directory $result_dir D -h $heuristic_1 -p $PREPROCESSOR -i $iterations

mvsed -s "s/\.dot/-D-$prefix${heuristic_1}_edge\.dot/" *.dot

$script_directory/runHeuristic $working_directory $result_dir DD -h $heuristic_2 -i $iterations
$script_directory/runHeuristicR $working_directory $result_dir DR -h $heuristic_2 -i $iterations

popd

#  [Last modified: 2015 08 29 at 01:24:14 GMT]
